### ISSUE TITLE
I get an error about no attribute 'character'

### ISSUE THREAD

**Issue by Mage-Enderman** [theubie/complex_memory#19]
"Traceback (most recent call last):
  File "G:\-AI\oobabooga_windows\text-generation-webui\server.py", line 1186, in <module>
    create_interface()
  File "G:\-AI\oobabooga_windows\text-generation-webui\server.py", line 1079, in create_interface
    extensions_module.create_extensions_block()
  File "G:\-AI\oobabooga_windows\text-generation-webui\modules\extensions.py", line 175, in create_extensions_block
    extension.ui()
  File "G:\-AI\oobabooga_windows\text-generation-webui\extensions\complex_memory\script.py", line 182, in ui
    load_pairs()
  File "G:\-AI\oobabooga_windows\text-generation-webui\extensions\complex_memory\script.py", line 84, in load_pairs
    if shared.character is not None and shared.character != "None":
AttributeError: module 'modules.shared' has no attribute 'character'"

**Comment by Xabab** [comment]
#18
