### ISSUE TITLE
Bug is back: AttributeError: module 'modules.shared' has no attribute 'character'

### ISSUE THREAD

**Issue by CognitiveDiffusion** [theubie/complex_memory#21]
So it seems like the bug is back (maybe Ooba was changed again?).

` File "E:\StableDiffusion\text-generation-webui\text-generation-webui\extensions\complex_memory\script.py", line 56, in save_pairs
    filename = f"characters/{shared.character}.json"
AttributeError: module 'modules.shared' has no attribute 'character'`

**Comment by ollybrain** [comment]
I have the same problem on Debian11:
--Unable to load complex memories for character AI.  filename: characters/AI.json.  Using defaults.
Traceback (most recent call last):
  File "/home/olly/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/olly/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/olly/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/olly/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/olly/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "/home/olly/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "/home/olly/Dokumente/oobabooga_linux/text-generation-webui/extensions/complex_memory/script.py", line 195, in update_pairs
    save_pairs()
  File "/home/olly/Dokumente/oobabooga_linux/text-generation-webui/extensions/complex_memory/script.py", line 56, in save_pairs
    filename = f"characters/{shared.character}.json"
AttributeError: module 'modules.shared' has no attribute 'character'
