### ISSUE TITLE
I cant get it to work

### ISSUE THREAD

**Issue by iceandstorm** [theubie/complex_memory#9]
Hi, I tried both, the direct copy in from the zip file and also the installation via pip. The files look identical with the git, but every time i want to load it (flag or via extension checkbox) I get this: 

C:\Projects\Text\oobabooga-windows\installer_files\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
--Unable to load complex memories for character AlpacaRadio.  filename: characters/AlpacaRadio.json.  Using defaults.
Traceback (most recent call last):
  File "C:\Projects\Text\oobabooga-windows\text-generation-webui\server.py", line 572, in <module>
    create_interface()
  File "C:\Projects\Text\oobabooga-windows\text-generation-webui\server.py", line 532, in create_interface
    extensions_module.create_extensions_block()
  File "C:\Projects\Text\oobabooga-windows\text-generation-webui\modules\extensions.py", line 69, in create_extensions_block
    extension.ui()
  File "C:\Projects\Text\oobabooga-windows\text-generation-webui\extensions\complex_memory\script.py", line 308, in ui
    [shared.gradio[k] for k in ['character_menu', 'name1', 'name2', 'mode']],
  File "C:\Projects\Text\oobabooga-windows\text-generation-webui\extensions\complex_memory\script.py", line 308, in <listcomp>
    [shared.gradio[k] for k in ['character_menu', 'name1', 'name2', 'mode']],
KeyError: 'mode'

**Comment by theubie** [comment]
I wasn't able to reproduce this.  When was the last time you updated you copy of text-generation-webui?

**Comment by iceandstorm** [comment]
Directly, before tried to get it to work.

**Comment by theubie** [comment]
`C:\Projects\Text\oobabooga-windows\installer_files\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
warnings.warn(value)`

That error was suppressed a couple of days ago.  Make sure your version to texe-generation-webui is actually updating.  It sounds like it's an older copy before they made all the changes to how the character menu was called.

**Comment by iceandstorm** [comment]
You were right! I had done some experiments with the gradio stuff, and the file was not updated because of uncommitted changes. Now, it seems to work. Thank you.
